const RETREIVE_FROM_BODY = "BODY";
const RETREIVE_FROM_HEADER = "HEADER";

const RETRIEVE_FORMS = [RETREIVE_FROM_BODY, RETREIVE_FROM_HEADER];

module.exports = {
  RETREIVE_FROM_BODY,
  RETREIVE_FROM_HEADER,
  RETRIEVE_FORMS,
};
