const FIX = "FIX";
const CURRENT = "CURRENT";
const FIRST_DATE_OF_CURRENT_MONTH = "FIRST_DATE_OF_CURRENT_MONTH";
const FIRST_DATE_OF_LAST_MONTH = "FIRST_DATE_OF_LAST_MONTH";
const FIRST_DATE_OF_NEXT_MONTH = "FIRST_DATE_OF_NEXT_MONTH";
const LAST_DATE_OF_CURRENT_MONTH = "LAST_DATE_OF_CURRENT_MONTH";
const LAST_DATE_OF_LAST_MONTH = "LAST_DATE_OF_LAST_MONTH";
const LAST_DATE_OF_NEXT_MONTH = "LAST_DATE_OF_NEXT_MONTH";

module.exports = {
  FIX,
  CURRENT,
  FIRST_DATE_OF_CURRENT_MONTH,
  FIRST_DATE_OF_LAST_MONTH,
  FIRST_DATE_OF_NEXT_MONTH,
  LAST_DATE_OF_CURRENT_MONTH,
  LAST_DATE_OF_LAST_MONTH,
  LAST_DATE_OF_NEXT_MONTH,
};
