const TIME_UNIT_MODIFY_TYPE_ADD = "ADD";
const TIME_UNIT_MODIFY_TYPE_SUBSTRACT = "SUBSTRACT";

const TIME_UNIT_MODIFY_TYPES = [
  TIME_UNIT_MODIFY_TYPE_ADD,
  TIME_UNIT_MODIFY_TYPE_SUBSTRACT,
];

module.exports = {
  TIME_UNIT_MODIFY_TYPE_ADD,
  TIME_UNIT_MODIFY_TYPE_SUBSTRACT,
  TIME_UNIT_MODIFY_TYPES,
};
