const VARIABLE_TYPE_DATE = "DATE";
const VARIABLE_TYPE_PREVIOUS_REQUEST = "PREVIOUS_REQUEST";

const VARIABLE_TYPES = [VARIABLE_TYPE_DATE, VARIABLE_TYPE_PREVIOUS_REQUEST];

module.exports = {
  VARIABLE_TYPE_DATE,
  VARIABLE_TYPE_PREVIOUS_REQUEST,
  VARIABLE_TYPES,
};
